### PR TITLE
Non-current activities: current date definition and XML output

### PR DESCRIPTION
**Pull request by Lathrisk**
This adds a date form field for the upload and download cells in the notebook.
This value is then used to calculate the current period (12 months prior to the specified date).
Closing #15 

A field has been added providing the user with the option to store all non-current activities in an XML file.
Partial #17 (no print/test list of identifiers and dates in the notebook) 

Dev notebook: https://colab.research.google.com/drive/1SPBUu8x0lB92SuH4rxTwukjaZu87Kja5

### CODE REVIEW

**Comment by Bjwebb** [comment]
@stevieflow Could you check this does what you expect?

**Comment by Lathrisk** [comment]
It would be nice if the form elements were conditionally rendered but that doesn't appear to be possible

**Comment by Bjwebb** [comment]
Yes, I thought the same, but didn't find a way.

**Comment by stevieflow** [comment]
Thanks   have added my review

> Dev notebook: https://colab.research.google.com/drive/1SPBUu8x0lB92SuH4rxTwukjaZu87Kja5

One note on the versions of the notebook - I was slightly thrown by this version, as it was a) read only and b) the same title as other docs.  In future, can we please use tags such as #dev in the title (and check it's not read only).  Thanks!

**Comment by Lathrisk** [comment]
Thanks, @stevieflow. We've been writing up a colab notebook collaborative dev process document (that's a mouthful) and I've added the hashtag point for future reference.

i.e. https://docs.google.com/document/d/1yd83JfvE4_cRoRyM5BGuk4A-GImY6HiZfZ9rkGpa5pA/edit

**Comment by Lathrisk** [comment]
This PR now also contains the option to output non-current activities to XML (the work for #17 can be split out of this PR if necessary).

**Comment by Bjwebb** [comment]
BTW, I'm happy to have multiple changes in a PR, because it is rather fiddly to separate out changes to a notebook.

**Comment by Lathrisk** [comment]
@stevieflow can you take a look at the new fix which adds the option to export the non-current activities as XML?

The issue (#17) also mentioned outputting a list in the notebook itself, is it just the activity identifiers that are needed as the output?

(same notebook as before, correctly tagged and titled this time: https://colab.research.google.com/drive/1SPBUu8x0lB92SuH4rxTwukjaZu87Kja5)

**Comment by stevieflow** [comment]
Thanks @Lathrisk 

Have tested, and generated an xml file with the expected number of activities

A list of : 
- activity-identifier
- activity-status/@code
- activity-date/@code + iso-date - for all dates in the activity

Would be great.  Whether that is easier (the example I tested had 1688 non-current activities) to write that to a file is another question.  Probably easier to do that?

**Comment by Bjwebb** [comment]
[IATI Colab notebooks 4.0](https://trello.com/c/vDm4sG1i/33-iati-colab-notebooks-40)

**Comment by Lathrisk** [comment]
@stevieflow I've added code my dev copy so that it outputs a list of all of the non-current activities. Is that the format in data you were expecting?

This is currently just text output in the colab notebook, but it does have the potential to be quite lengthy. We can set this up to output to file, and can also change the format into CSV or suchlike.

https://colab.research.google.com/drive/1SPBUu8x0lB92SuH4rxTwukjaZu87Kja5

**Comment by stevieflow** [comment]
@Lathrisk thanks.  Please can you check - I *think* that with the print of non-current activities, the onscreen statement to say how many activities were kept/lost - was lost... that was really useful to me (although I didnt tell you!)!

**Comment by Lathrisk** [comment]
@stevieflow it looks like it has truncated the output to 5000 lines (favouring the end). It _should_ still display the number of non-current activities in the summary (but that's at the start). This is definitely a good reason to output to file. I'll get that updated soon.

**Comment by stevieflow** [comment]
Thanks @Lathrisk 

Yeah - no need to output the list to screen - a file is suffice

The stats are useful though

**Comment by Lathrisk** [comment]
@stevieflow I've updated the notebook so that it outputs the text to file, and should list the total number of non-current activities in the notebook and at the top of the output file.

**Comment by stevieflow** [comment]
Thanks @Lathrisk 

> the output file.

Just observing that this is a .xml file.  Should it be a .txt file?

**Comment by Lathrisk** [comment]
@stevieflow yes. A good old copy and paste error. Thanks for the heads up, should be sorted now!

**Pull request merged**
