### PR TITLE
filtering: Add filter for activity-status

### PR DESCRIPTION
**Pull request by Lathrisk**
### [Master Colab Notebook](https://colab.research.google.com/drive/1UihxpcixZGbHOYf5EDyMY_uX1zQR33Yu#scrollTo=IYvJofhk8g1R)

### CODE REVIEW

**Review by Bjwebb — APPROVED** [review]

**Review by Bjwebb — CHANGES_REQUESTED** [review]
Code is good. Could you add a description for the change to the table at the top?

This also needs copying onto the "#master" notebook, and rerunning for dipr, probably without this filter. It would be good if you could do this, but maybe a call is best for me to explain the details of how its done (particularly the copying back on to "#master").

**Comment by BibianaC** [comment]
@Lathrisk is this PR still relevant?

**Comment by Lathrisk** [comment]
@BibianaC Yes, I suspect it is. The feature hasn't been requested for a while but it also hasn't been merged into master. I think I should still do that. Thanks for the reminder too.

**Comment by Lathrisk** [comment]
@Bjwebb This is a little stale, but I have finally updated the changelog table. I assume that was the requested change. Do we still want to merge this? :grimacing:

**Review by Bjwebb — APPROVED** [review]

**Comment by Bjwebb** [comment]
I've updated the [#master colab notebook](https://colab.research.google.com/drive/1UihxpcixZGbHOYf5EDyMY_uX1zQR33Yu#scrollTo=l-_7aD4n3fvS).

**Comment by Lathrisk** [comment]
Thanks, @Bjwebb :tada:

**Pull request merged**
